Added my personal page
BuidlGuidl/batch7.buidlguidl.com pull request #16
Opened 2024-07-11 15:14 UTC by Ursulovic

## Description

_Concise description of proposed changes, We recommend using screenshots and videos for better description_

## Additional Information

- [ ] I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [ ] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)

## Related Issues

_Closes #{issue number}_

_Note: If your changes are small and straightforward, you may skip the creation of an issue beforehand and remove this section. However, for medium-to-large changes, it is recommended to have an open issue for discussion and approval prior to submitting a pull request._

Your ENS/address:

2024-07-11 16:18 UTC, carletex commented on packages/nextjs/app/builders/0x8EC90502356657Cc30f22444A8e073FE89322333/page.tsx
Since you are using "hardcoded" TW classes, the page looks the same in light / dark mode (you can switch from the right bottom switcher).

A couple of options:

- Use the `dark:<whatevercolor>` TW selector, 
- Use daisy themes classes like "bg-primary", "text-secondary", etc (check packages/nextjs/tailwind.config.js)

2024-07-11 16:19 UTC, carletex commented on packages/nextjs/app/builders/0x8EC90502356657Cc30f22444A8e073FE89322333/page.tsx
![image](https://github.com/BuidlGuidl/batch7.buidlguidl.com/assets/2486142/21b9ad50-2c65-47e3-824d-13591cbdee1c)

It could use a little bit of padding on the sides (when on mobile at least!)

2024-07-11 16:19 UTC, carletex commented on packages/nextjs/app/builders/0x8EC90502356657Cc30f22444A8e073FE89322333/page.tsx
> +const HomePage = () => {
Let's use a better const name (instead of HomePage, something like IvanBuilderPage)

2024-07-11 16:22 UTC, carletex requested changes
Good stuff @Ursulovic !!

Left a few review comments. No one is a big deal, but good to get some practice with best practices in SE-2!

P.S. The PR description is the placeholder we have, you could have written some descriptive text (a good example: https://github.com/BuidlGuidl/batch7.buidlguidl.com/pull/12)

2024-07-12 08:36 UTC, Ursulovic commented
Hi, in most recent commit I hope I have fixed all the issues :)

2024-07-15 09:46 UTC, carletex commented on packages/nextjs/app/builders/0x8EC90502356657Cc30f22444A8e073FE89322333/page.tsx
> +  }, []);
This shouldn't be needed! Since it's already handled by SE-2.

2024-07-15 09:47 UTC, carletex requested changes
Hey @Ursulovic added a comment regarding the dark logic

2024-07-15 17:41 UTC, Ursulovic commented
Removed unneeded parts of code regarding dark logic, also changed color of text to improve visibility.

2024-07-16 08:41 UTC, merged

2024-07-16 08:41 UTC, carletex commented
Great! Merging